export enum NotificationType {
  ARTWORK_LIKE = 'ARTWORK_LIKE',
  ARTWORK_COMMENT = 'ARTWORK_COMMENT',
  FOLLOW = 'FOLLOW',

  MOMENT_LIKE = 'MOMENT_LIKE',
  MOMENT_COMMENT = 'MOMENT_COMMENT',

  ARTWORK_DELETED_BY_ADMIN = 'ARTWORK_DELETED_BY_ADMIN',
}
